Creates a developer environment using express
rugpullindex/design-system pull request #26
Opened 2021-12-01 00:32 UTC by d80ep08th

fixes #19

Creates a process that requests rugpullindex.com 's index side. 
Serves this content to a developer after running : npm run dev

2021-12-02 19:31 UTC, il3ven commented
@d80ep08th The node_modules are still on your branch. Follow the steps here to remove them. https://stackoverflow.com/a/1139797

2021-12-03 09:17 UTC, TimDaub commented
There were two commits that included all `node_modules`, so I had to do some rebasing to clean up the branch on your remote @d80ep08th. It's now ready for review.

2021-12-03 09:23 UTC, TimDaub requested changes
It works, but I found a functional bug. To reproduce:

1. Run `npm run dev`, check localhost:5000, website works and everything runs fine
2. Kill the process
3. Rerun `npm run dev`, now we get an error message

```
> design-system@1.0.0 dev /Users/user/Projects/rpi-design-system
> nodemon index.js

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
rugpullindex runs on localhost:5000/
[Error: EEXIST: file already exists, mkdir '/Users/user/Projects/rpi-design-system/cache'] {
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/Users/user/Projects/rpi-design-system/cache'
}
```

Also: We should put the `cache` folder in `.gitignore` too.

2021-12-03 12:57 UTC, TimDaub approved these changes

2021-12-03 12:57 UTC, merged